### ISSUE TITLE
Add name of result_set (name of suite) on result set page

### ISSUE THREAD

**Issue by ShockwaveNN** [flaminestone/palladium-old#12]

**Comment by flaminestone** [comment]
You tell about name of result_set (name of suite) on result page (not on result set page).
I have add navigation link. It is it?
![sketch-1472766360056](https://cloud.githubusercontent.com/assets/6047261/18185526/cc15e746-70a6-11e6-97cf-6c084de58db2.png)

**Comment by ShockwaveNN** [comment]
@flaminestone Looks like it, thanks
